name: Maven Central Package Publish CI

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Package Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set Up Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN}}

      - name: Set Up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install GPG
        run: brew install gpg

      - name: Create Secring
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "${SIGNING_KEY}" | gpg --dearm > ${HOME}/secring.gpg

      - name: Add Gradle Properties
        env:
          MAVEN_CENTRAL_USER_NAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          mkdir -p ${HOME}/.gradle
          touch ${HOME}/.gradle/gradle.properties
          echo "mavenCentralUsername=${MAVEN_CENTRAL_USER_NAME}" >> ${HOME}/.gradle/gradle.properties
          echo "mavenCentralPassword=${MAVEN_CENTRAL_PASSWORD}" >> ${HOME}/.gradle/gradle.properties
          echo "signing.keyId=${SIGNING_KEY_ID}" >> ${HOME}/.gradle/gradle.properties
          echo "signing.password=${SIGNING_KEY_PASSWORD}" >> ${HOME}/.gradle/gradle.properties
          echo "signing.secretKeyRingFile=${HOME}/secring.gpg" >> ${HOME}/.gradle/gradle.properties

      - name: Check Gradle Properties Data
        run: cat ${HOME}/.gradle/gradle.properties

      - name: Build Project
        run: task build

      - name: Publish To Maven Central
        run: task publish
